import type { Metadata } from "next";
import { ImageSlot } from "@/components/image-slot";
import { MoreServices } from "@/components/more-services";

export const metadata: Metadata = { title: "Services" };

const moreServices = [
  ["Addiction", "Support for understanding patterns of substance use and building healthier ways of coping and living."],
  ["Codependency", "Develop healthier boundaries, strengthen self-awareness, and build more balanced relationships."],
  ["Divorce", "Support through the emotional challenges of separation, transition, and creating a new sense of direction."],
  ["Geriatric & Seniors", "Compassionate support for life transitions, aging, loss, relationships, and finding meaning later in life."],
  ["Grief", "A supportive space to process loss, honor what has changed, and find a way forward."],
  ["Infidelity", "Explore betrayal, trust, communication, and the difficult decisions that follow infidelity."],
  ["Marital & Premarital", "Strengthen communication, deepen connection, and navigate challenges within committed relationships."],
  ["Parenting", "Support for navigating parenting challenges, family dynamics, boundaries, and the demands of raising children."],
  ["Personality Disorders", "Develop deeper self-understanding and explore patterns that affect emotions, identity, and relationships."],
  ["Stress", "Learn to understand sources of stress and develop healthier ways to respond to life’s demands."],
  ["Trauma & PTSD", "A safe, supportive space to process difficult experiences and work toward greater stability and healing."],
  ["Women’s Issues", "Support for navigating the unique emotional, relational, and life experiences that affect women’s well-being."],
];

export default function ServicesPage() {
  return (
    <main className="content-page wrap services-page">
      <ImageSlot src="/images/service-individual.jpg" alt="Individual therapy session" label="Individual therapy image" className="service-feature-image" />
      <section className="prose"><h1>Individual Therapy</h1><p>I work with men and women who want to understand themselves more deeply and create meaningful, lasting change in their lives. People come to therapy for many different reasons: depression, anxiety, trauma, relationship difficulties, loneliness, loss, immigration and cultural adjustment, career or life transitions, or simply a persistent feeling that something is missing or no longer working. I believe symptoms often carry meaning. Rather than focusing only on making them disappear, we become curious about what lies beneath them: the experiences, relationships, unconscious patterns, and ways of protecting yourself that may have once been necessary but may now be limiting your life.</p><p>My approach is collaborative, warm, and depth-oriented. Together, we explore not only what is happening, but also why it may be happening and what it means to you. Through psychoanalytic and existential perspectives, we can begin to recognize recurring patterns, understand how the past continues to live in the present, and create greater freedom to choose rather than simply repeat. Therapy becomes a place to know yourself more fully, to develop a stronger and more authentic sense of self, deepen your relationships, navigate change with greater awareness, and discover what gives your life meaning, connection, and purpose.</p></section>
      <ImageSlot src="/images/service-couples.jpg" alt="Couples therapy session" label="Couples therapy image" className="service-feature-image" />
      <section className="prose"><h2>Couples Therapy</h2><p>I especially enjoy working with couples and helping partners understand not only the conflicts that bring them to therapy, but the deeper emotional patterns beneath them. Couples often find themselves repeating the same arguments, feeling increasingly distant, misunderstood, or unable to reach one another despite still caring deeply about the relationship. In our work together, we look beyond who is right or wrong and become curious about what is happening between you, the unspoken needs, fears, expectations, attachment patterns, and past experiences that each partner brings into the relationship. What appears to be a conflict about communication, intimacy, parenting, money, or everyday responsibilities often carries a much deeper emotional meaning.</p><p>My approach to couples therapy is warm, collaborative, and nonjudgmental. I strive to create a space where both partners can feel heard and understood, while also helping each person recognize their contribution to the patterns that have developed between them. Drawing from psychoanalytic, attachment, existential, and systemic perspectives, we explore how individual histories become intertwined within the relationship and how the couple can begin to relate to one another differently. The goal is not simply to stop arguing, but to develop greater emotional intimacy, authenticity, trust, and understanding, creating a relationship in which both people can remain connected while also growing more fully into themselves.</p></section>
      <ImageSlot src="/images/service-family.jpg" alt="Family therapy session" label="Teen and family therapy image" className="service-feature-image" />
      <section className="prose"><h2>Teen and Family Therapy</h2><p>I hold a deep belief that children and teenagers are rarely “the problem.” Often, their emotions and behaviors can be understood as meaningful responses to what they are experiencing within their family, relationships, school, or broader environment. Young people can become remarkably sensitive mirrors of the emotional world around them, sometimes expressing through anxiety, anger, withdrawal, sadness, or behavior what may be difficult for the family as a whole to recognize or put into words. For this reason, I approach teenagers with curiosity rather than judgment. I do not begin by asking, “What is wrong with this child?” but rather, “What is this young person experiencing, and what might they be trying to communicate?” My goal is to create a safe relationship in which a teenager can gradually feel understood, develop a stronger sense of self, and find healthier ways to express emotions and navigate the challenges of growing up.</p><p>At the same time, I approach parents with the same compassion and respect. Parenting is one of the most difficult, complex, and emotionally demanding roles a person can undertake, and I do not believe in pathologizing or blaming parents when a family is struggling. Families can become caught in painful patterns even when everyone involved is trying their best. When appropriate, I work with both the teenager and the family to understand these patterns, improve communication, clarify boundaries, and create opportunities for genuine reconnection. Rather than searching for someone to blame, we work together to understand what has happened between family members and, most importantly, how they can begin to find their way back to one another.</p></section>
      <ImageSlot src="/images/service-intensive.jpg" alt="An extended psychotherapy session" label="Therapy intensive image" className="service-feature-image" />
      <section className="prose development"><p className="eyebrow">Development in Progress</p><h2>Depth &amp; Meaning Therapy Intensive</h2><p>A Five-Hour Immersive Psychotherapy Experience offers an extended therapeutic space for people who want the opportunity to explore important emotional concerns, recurring patterns, relationships, identity, life transitions, and questions of meaning without the limitations of the traditional 50-minute hour. The five-hour format, with short restorative breaks, allows us to stay with important material as it unfolds, follow associations more deeply, make connections between past and present, and allow time for reflection and integration. It can be particularly valuable for busy professionals, high achievers, creatives, first responders, and others whose demanding schedules make weekly psychotherapy difficult, as well as for existing clients who have reached a point in their therapy where an extended session may support deeper exploration. The Intensive is not intended to promise faster results or manufacture a “breakthrough”; rather, it provides something increasingly difficult to find in everyday life—several protected hours devoted entirely to understanding yourself more deeply.</p><p>Because extended psychotherapy can bring forward powerful emotions, memories, grief, unresolved conflicts, or unexpected insights, an Intensive may also leave a person feeling emotionally tired, vulnerable, unsettled, or in need of additional support afterward. For this reason, new patients are required to complete at least two preliminary sessions before an Intensive so that we can establish rapport, understand your history and current circumstances, assess whether this format is appropriate, and prepare for the experience together. Short breaks are incorporated throughout the five hours, and time at the end is reserved for integration and grounding. An integration session is scheduled for the following week, and the therapeutic connection does not abruptly end when the five hours are over: you are welcome to contact me afterward, including by phone when clinically appropriate, if something significant arises from the Intensive that needs to be addressed. The goal is not simply to go further in one day, but to create a thoughtful, contained therapeutic experience with preparation, depth, integration, and continuity of care.</p></section>
      <section className="film-consultation"><div className="prose"><h2>Psychological Consultation for Film</h2><p>Compelling characters are rarely simply “good,” “bad,” “healthy,” or “disturbed”; they are just like us: psychologically complex human beings shaped by their histories, relationships, desires, fears, conflicts, and unconscious motivations. I provide psychological consultation for screenwriters, filmmakers, directors, and other creative professionals seeking to bring greater psychological depth, authenticity, and emotional truth to their work.</p><p>Consultation may include developing psychologically believable characters and backstories, exploring conscious and unconscious motivations and relationship dynamics, portraying trauma and mental health conditions with accuracy and sensitivity, and considering how a character’s inner world might realistically shape their choices, behavior, dialogue, and transformation throughout a story.</p></div><ImageSlot src="/images/service-film.jpg" alt="Film character consultation" label="Film consultation image" /></section>
      <MoreServices services={moreServices} />
    </main>
  );
}
